name: Deploy-Vote
on:
  push:
    branches:
      - master
      
jobs:
  Clone-to-ubuntu:
    name: Clone repo on ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pwd && ls