name: Deploy-Vote
on:
  push:
    branches:
      - master
      
jobs:
  Clone-to-ubuntu:
    name: Clone repo on ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cp -rf /home/runner/work/teste-lion-sre/teste-lion-sre/example-voting-app /app