name: Deploy-Vote
on:
  push:
    branches:
      - master
      
jobs:
  ECR-auth:
    name: ECR-auth
    runs-on: self-hosted
    steps:
      - name: Auth AWS ECR
        run: aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 939558840714.dkr.ecr.us-east-1.amazonaws.com

  Clone-to-ubuntu:
    name: Clone repo on ubuntu
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: cp -rf ./voting-app ~/app

  build-vote:
    name: build-vote
    needs:
      - Clone-to-ubuntu
      - ECR-auth
    runs-on: self-hosted
    steps:
      - name: Create Docker Image
        run: whoami && cd ~/app/voting-app/vote/ && sudo docker build -t matheus.leao-vote-ecr-dev/vote:latest .
      - name: Tag image
        run: sudo docker tag matheus.leao-vote-ecr-dev/vote:lastest 939558840714.dkr.ecr.us-east-1.amazonaws.com/matheus.leao-vote-ecr-dev:${{ github.sha }}
      - name: Pull image
        run: sudo docker push 939558840714.dkr.ecr.us-east-1.amazonaws.com/matheus.leao-vote-ecr-dev:${{ github.sha }}

  deploy-vote:
    name: deploy-vote
    needs: build-vote
    runs-on: self-hosted
    steps:
      - name: Replace Docker Image
        run: cd ~/app && sed -i 's/hash/${{ github.sha }}/g' ./voting-app/k8s-specifications/vote-deployment.yaml
      - name: Deploy to k8s
        run: cd ~/app && microk8s kubectl apply -f ./voting-app/k8s-specifications/vote-deployment.yaml