name: Deploy-Vote
on:
  push:
    branches:
      - master
      
jobs:
  Clone-to-ubuntu:
    name: Clone repo on ubuntu
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: cp -rf ./voting-app ~/app

  build:
    name: build
    needs: Clone-to-ubuntu
    runs-on: self-hosted
    steps:
      - name: Deploy to k8s
        run: cd ~/app && microk8s kubectl create -f ./voting-app/k8s-specifications/