name: Deploy-Vote
on:
  push:
    branches:
      - master
      
jobs:
  Clone-to-ubuntu:
    name: Clone repo on ubuntu
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: cp -rf ./voting-app ~/app

  build-vote:
    name: build-vote
    needs: Clone-to-ubuntu
    runs-on: self-hosted
    steps:
      - name: Create Docker Image
        run: whoami && cd ~/app/voting-app/vote/ && sudo docker build -t vote-app/vote:${{ github.sha }} .

  deploy-vote:
    name: deploy-vote
    needs: build-vote
    runs-on: self-hosted
    steps:
      - name: Replace Docker Image
        run: cd ~/app && sed -i 's/hash/${{ github.sha }}/g' ./voting-app/k8s-specifications/vote-deployment.yaml
      - name: Deploy to k8s
        run: cd ~/app && microk8s kubectl apply -f ./voting-app/k8s-specifications/vote-deployment.yaml